/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#673d00",
        "on-secondary": "#30312e",
        "primary-fixed": "#e9ddff",
        "on-secondary-fixed": "#1b1c1a",
        "error-container": "#93000a",
        error: "#ffb4ab",
        tertiary: "#ffb869",
        "inverse-surface": "#d9e3f6",
        secondary: "#c8c6c3",
        "surface-tint": "#d0bcff",
        "on-error": "#690005",
        "on-tertiary-fixed": "#2c1700",
        "on-primary": "#3c0091",
        "surface-container-highest": "#2b3544",
        "primary-fixed-dim": "#d0bcff",
        "on-secondary-fixed-variant": "#474744",
        "on-surface": "#d9e3f6",
        "secondary-container": "#474744",
        "tertiary-fixed-dim": "#ffb869",
        background: "#091421",
        "surface-container-high": "#212b39",
        "on-primary-fixed-variant": "#5516be",
        outline: "#958ea0",
        "on-primary-container": "#340080",
        "on-primary-fixed": "#23005c",
        "tertiary-container": "#ca801e",
        "on-error-container": "#ffdad6",
        "on-background": "#d9e3f6",
        "surface-dim": "#091421",
        "inverse-primary": "#6d3bd7",
        "surface-container": "#16202e",
        "surface-variant": "#2b3544",
        "outline-variant": "#494454",
        surface: "#091421",
        "on-surface-variant": "#cbc3d7",
        "on-secondary-container": "#b6b5b1",
        "primary-container": "#a078ff",
        "inverse-on-surface": "#27313f",
        "on-tertiary": "#482900",
        "surface-bright": "#303a48",
        "secondary-fixed-dim": "#c8c6c3",
        primary: "#d0bcff",
        "on-tertiary-container": "#3f2300",
        "surface-container-low": "#121c2a",
        "surface-container-lowest": "#050f1c",
        "secondary-fixed": "#e4e2de",
        "tertiary-fixed": "#ffdcbb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "touch-target-min": "48px",
        gutter: "16px",
        "stack-sm": "8px",
        "margin-mobile": "20px",
        "stack-lg": "24px",
        "stack-md": "16px",
      },
      fontFamily: {
        "label-caps": ["System"],
        "numeric-data": ["System"],
        "display-lg": ["System"],
        "body-lg": ["System"],
        "headline-md": ["System"],
        "body-base": ["System"],
        "display-xl": ["System"],
      },
    },
  },
  plugins: [],
}
